[package]
name = "imp-remote-cache"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
opendal = { workspace = true, features = ["services-ghac", "reqwest-rustls-tls", "layers-retry"] }

[dev-dependencies]
opendal = { workspace = true, features = ["services-ghac", "services-memory"] }
tokio.workspace = true
