[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
tokio        = { version = "1",    features = ["full"] }
clap         = { version = "4",    features = ["derive", "string"] }
indicatif    = "0.18"
anyhow       = "1"
async-trait  = "0.1"
serde        = { version = "1",    features = ["derive"] }
serde_json   = "1"
walkdir      = "2"
regex        = "1"
rusqlite     = { version = "0.31", features = ["bundled"] }
sha2         = "0.10"
tempfile     = "3"
futures      = { version = "0.3", default-features = false, features = ["std"] }
rquickjs     = { version = "0.12", features = ["loader", "futures", "macro"] }
signal-hook  = "0.4"
log          = "0.4"
include_dir  = "0.7"
tonic        = "0.12"
prost        = "0.13"
tonic-build  = "0.12"
protox       = "0.7"
tokio-stream = { version = "0.1", features = ["net"] }
hyper-util   = { version = "0.1", features = ["tokio"] }
tower        = "0.5"

[package]
name = "imp"
version.workspace = true
edition.workspace = true

[[bin]]
name = "imp"
path = "src/main.rs"

[dependencies]
imp-store = { path = "crates/imp-store" }
imp-exec-api = { path = "crates/imp-exec-api" }
imp-execution = { path = "crates/imp-execution", features = ["clap"] }
imp-daemon = { path = "crates/imp-daemon" }
tokio.workspace = true
clap.workspace = true
indicatif.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
walkdir.workspace = true
regex.workspace = true
rusqlite.workspace = true
sha2.workspace = true
tempfile.workspace = true
futures.workspace = true
rquickjs.workspace = true
signal-hook.workspace = true
log.workspace = true
include_dir.workspace = true

[profile.dev]
opt-level = 1
