[package]
name = "imp"
version.workspace = true
edition.workspace = true

[[bin]]
name = "imp"
path = "src/main.rs"

[dependencies]
imp-store = { path = "../imp-store" }
imp-execution = { path = "../imp-execution", features = ["clap"] }
imp-daemon = { path = "../imp-daemon" }
imp-engine = { path = "../imp-engine" }
imp-logging = { path = "../imp-logging" }
imp-scheduler = { path = "../imp-scheduler" }
tokio.workspace = true
clap.workspace = true
indicatif.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
walkdir.workspace = true
regex.workspace = true
tempfile.workspace = true
rquickjs.workspace = true
signal-hook.workspace = true
log.workspace = true
dialoguer.workspace = true

[dev-dependencies]
imp-engine = { path = "../imp-engine", features = ["test-support"] }
