import { cargoPackage } from "//rules/rust";
import { protoAssets } from "//crates/imp-daemon";
import {
    engineAssets,
    testTar,
    testGzip,
    testGit,
    testCmake,
    testCc,
    testAs,
    testLd,
    testAr,
    testMkdir,
    testNinja,
    testDirname,
    testCp,
    testCtest,
    testFind,
    testSed,
    testSha256sum,
    testCurl,
    testWc,
    testXz,
    testChmod,
} from "//";

export const imp_engine = cargoPackage({
    deps: [engineAssets, protoAssets],
    testTools: [
        testTar,
        testGzip,
        testGit,
        testCmake,
        testCc,
        testAs,
        testLd,
        testAr,
        testMkdir,
        testNinja,
        testDirname,
        testCp,
        testCtest,
        testFind,
        testSed,
        testSha256sum,
        testCurl,
        testWc,
        testXz,
        testChmod,
    ],
    workspaceMember: true,
});
