[package]
name = "imp-daemon"
version.workspace = true
edition.workspace = true
build = "build.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
prost.workspace = true
tokio.workspace = true
tonic.workspace = true
tokio-stream.workspace = true
imp-exec-api = { path = "../imp-exec-api" }
imp-execution = { path = "../imp-execution" }
imp-store = { path = "../imp-store" }

[build-dependencies]
protox.workspace = true
tonic-build.workspace = true
