base_url = "https://imps.build"

title = "imp"
description = "A hermetic, content-addressed build system."

compile_sass = false
build_search_index = false

[markdown.highlighting]
style = "inline"
theme = "Dracula"

[extra]
